CREATE TABLE tasks (
    id INT IDENTITY (1,1) PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    full_name VARCHAR (100) NOT NULL,
    email VARCHAR (100) NOT NULL,
    created_at DATETIME NOT NULL
);